-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.clinics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  doctor_name text NOT NULL,
  specialty text,
  description text,
  address text,
  city text,
  country text DEFAULT 'India'::text,
  phone text,
  email text,
  website text,
  logo_url text,
  widget_theme_color text DEFAULT '#0071E3'::text,
  widget_tone text DEFAULT 'professional'::text,
  timezone text DEFAULT 'Asia/Kolkata'::text,
  language USER-DEFINED DEFAULT 'en'::language_code,
  slot_duration_minutes integer DEFAULT 30,
  buffer_time_minutes integer DEFAULT 0,
  max_advance_days integer DEFAULT 30,
  min_notice_hours integer DEFAULT 2,
  notification_channel USER-DEFINED DEFAULT 'email'::notification_channel,
  whatsapp_number text,
  email_notifications boolean DEFAULT true,
  plan USER-DEFINED DEFAULT 'free'::subscription_plan,
  plan_status USER-DEFINED DEFAULT 'trial'::subscription_status,
  trial_ends_at timestamp with time zone DEFAULT (now() + '14 days'::interval),
  stripe_customer_id text,
  stripe_subscription_id text,
  slug text UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clinics_pkey PRIMARY KEY (id),
  CONSTRAINT clinics_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.services (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  duration_minutes integer NOT NULL DEFAULT 30,
  price numeric,
  currency text DEFAULT 'INR'::text,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  name_hi text,
  description_hi text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT services_pkey PRIMARY KEY (id),
  CONSTRAINT services_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.availability (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  is_available boolean DEFAULT true,
  start_time time without time zone NOT NULL DEFAULT '09:00:00'::time without time zone,
  end_time time without time zone NOT NULL DEFAULT '17:00:00'::time without time zone,
  break_start time without time zone,
  break_end time without time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT availability_pkey PRIMARY KEY (id),
  CONSTRAINT availability_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.blocked_dates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  blocked_date date NOT NULL,
  reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT blocked_dates_pkey PRIMARY KEY (id),
  CONSTRAINT blocked_dates_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.patients (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  name text NOT NULL,
  email text,
  phone text,
  date_of_birth date,
  gender text,
  address text,
  notes text,
  preferred_language USER-DEFINED DEFAULT 'en'::language_code,
  total_appointments integer DEFAULT 0,
  last_appointment_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT patients_pkey PRIMARY KEY (id),
  CONSTRAINT patients_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.appointments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  patient_id uuid,
  service_id uuid,
  patient_name text NOT NULL,
  patient_email text,
  patient_phone text,
  service_name text,
  duration_minutes integer DEFAULT 30,
  appointment_date date NOT NULL,
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::appointment_status,
  patient_notes text,
  doctor_notes text,
  booked_via text DEFAULT 'widget'::text,
  booking_language USER-DEFINED DEFAULT 'en'::language_code,
  confirmation_sent boolean DEFAULT false,
  reminder_sent boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT appointments_pkey PRIMARY KEY (id),
  CONSTRAINT appointments_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT appointments_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT appointments_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.ai_knowledge (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  question text NOT NULL,
  answer text NOT NULL,
  question_hi text,
  answer_hi text,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_knowledge_pkey PRIMARY KEY (id),
  CONSTRAINT ai_knowledge_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.chat_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  appointment_id uuid,
  session_token text NOT NULL,
  completed_booking boolean DEFAULT false,
  messages_count integer DEFAULT 0,
  language_used USER-DEFINED DEFAULT 'en'::language_code,
  started_at timestamp with time zone DEFAULT now(),
  ended_at timestamp with time zone,
  duration_seconds integer,
  CONSTRAINT chat_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT chat_sessions_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT chat_sessions_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id)
);
CREATE TABLE public.notification_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  appointment_id uuid,
  channel USER-DEFINED NOT NULL,
  recipient text NOT NULL,
  type text NOT NULL,
  status text DEFAULT 'sent'::text,
  error_message text,
  sent_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_logs_pkey PRIMARY KEY (id),
  CONSTRAINT notification_logs_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT notification_logs_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id)
);
CREATE TABLE public.analytics_snapshots (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  snapshot_date date NOT NULL,
  total_appointments integer DEFAULT 0,
  confirmed_count integer DEFAULT 0,
  completed_count integer DEFAULT 0,
  cancelled_count integer DEFAULT 0,
  no_show_count integer DEFAULT 0,
  new_patients integer DEFAULT 0,
  widget_sessions integer DEFAULT 0,
  bookings_via_widget integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT analytics_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT analytics_snapshots_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.ai_companion_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL UNIQUE,
  is_enabled boolean DEFAULT true,
  triage_enabled boolean DEFAULT true,
  triage_sensitivity text DEFAULT 'moderate'::text CHECK (triage_sensitivity = ANY (ARRAY['low'::text, 'moderate'::text, 'high'::text])),
  symptom_checker_enabled boolean DEFAULT true,
  restricted_topics ARRAY DEFAULT '{}'::text[],
  max_messages_per_session integer DEFAULT 20,
  session_timeout_minutes integer DEFAULT 30,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_companion_settings_pkey PRIMARY KEY (id),
  CONSTRAINT ai_companion_settings_clinic_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.voice_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL UNIQUE,
  is_enabled boolean DEFAULT false,
  default_language text DEFAULT 'en'::text CHECK (default_language = ANY (ARRAY['en'::text, 'hi'::text])),
  fallback_language text DEFAULT 'en'::text,
  auto_detect_language boolean DEFAULT true,
  voice_gender text DEFAULT 'female'::text CHECK (voice_gender = ANY (ARRAY['male'::text, 'female'::text])),
  speech_rate numeric DEFAULT 1.0,
  noise_cancellation boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT voice_settings_pkey PRIMARY KEY (id),
  CONSTRAINT voice_settings_clinic_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.rag_documents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  title text NOT NULL,
  content text NOT NULL,
  source_type text DEFAULT 'manual'::text CHECK (source_type = ANY (ARRAY['manual'::text, 'upload'::text, 'auto_generated'::text])),
  file_url text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rag_documents_pkey PRIMARY KEY (id),
  CONSTRAINT rag_documents_clinic_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.rag_chunks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  document_id uuid NOT NULL,
  content text NOT NULL,
  embedding USER-DEFINED,
  token_count integer,
  chunk_index integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rag_chunks_pkey PRIMARY KEY (id),
  CONSTRAINT rag_chunks_clinic_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT rag_chunks_document_fkey FOREIGN KEY (document_id) REFERENCES public.rag_documents(id)
);
CREATE TABLE public.doctor_assistant_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL UNIQUE,
  is_enabled boolean DEFAULT true,
  auto_generate_on_open boolean DEFAULT true,
  summary_depth text DEFAULT 'standard'::text CHECK (summary_depth = ANY (ARRAY['brief'::text, 'standard'::text, 'detailed'::text])),
  show_risk_flags boolean DEFAULT true,
  show_medication_history boolean DEFAULT true,
  show_visit_patterns boolean DEFAULT true,
  show_recommendations boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT doctor_assistant_settings_pkey PRIMARY KEY (id),
  CONSTRAINT doctor_assistant_settings_clinic_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.visit_notes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  appointment_id uuid NOT NULL UNIQUE,
  patient_id uuid NOT NULL,
  subjective text,
  objective text,
  assessment text,
  plan text,
  ai_summary text,
  ai_risk_flags ARRAY DEFAULT '{}'::text[],
  follow_up_recommended boolean DEFAULT false,
  follow_up_days integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT visit_notes_pkey PRIMARY KEY (id),
  CONSTRAINT visit_notes_clinic_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT visit_notes_appointment_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT visit_notes_patient_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id)
);
CREATE TABLE public.prescriptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  appointment_id uuid NOT NULL,
  patient_id uuid NOT NULL,
  visit_note_id uuid,
  medicines jsonb NOT NULL DEFAULT '[]'::jsonb,
  diagnosis text,
  advice text,
  follow_up_date date,
  pdf_url text,
  is_sent boolean DEFAULT false,
  sent_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT prescriptions_pkey PRIMARY KEY (id),
  CONSTRAINT prescriptions_patient_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT prescriptions_clinic_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT prescriptions_appointment_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT prescriptions_visit_note_fkey FOREIGN KEY (visit_note_id) REFERENCES public.visit_notes(id)
);
CREATE TABLE public.prescription_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL UNIQUE,
  is_enabled boolean DEFAULT true,
  auto_send_email boolean DEFAULT true,
  template_style text DEFAULT 'standard'::text CHECK (template_style = ANY (ARRAY['standard'::text, 'minimal'::text, 'detailed'::text])),
  header_text text,
  footer_text text,
  show_logo boolean DEFAULT true,
  show_doctor_signature boolean DEFAULT true,
  signature_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT prescription_settings_pkey PRIMARY KEY (id),
  CONSTRAINT prescription_settings_clinic_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.patient_health_timeline (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  patient_id uuid NOT NULL,
  appointment_id uuid,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['visit'::text, 'prescription'::text, 'follow_up'::text, 'note'::text, 'ai_insight'::text])),
  title text NOT NULL,
  summary text,
  data jsonb DEFAULT '{}'::jsonb,
  ai_generated boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT patient_health_timeline_pkey PRIMARY KEY (id),
  CONSTRAINT patient_health_timeline_clinic_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT patient_health_timeline_patient_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT patient_health_timeline_appointment_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id)
);
CREATE TABLE public.followup_sequence_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL UNIQUE,
  is_enabled boolean DEFAULT true,
  step1_enabled boolean DEFAULT true,
  step1_delay_days integer DEFAULT 1,
  step1_subject text DEFAULT 'How are you feeling after your visit?'::text,
  step1_template text,
  step2_enabled boolean DEFAULT true,
  step2_delay_days integer DEFAULT 3,
  step2_subject text DEFAULT 'Medication reminder'::text,
  step2_template text,
  step3_enabled boolean DEFAULT true,
  step3_delay_days integer DEFAULT 7,
  step3_subject text DEFAULT 'Follow-up check-in'::text,
  step3_template text,
  step4_enabled boolean DEFAULT true,
  step4_delay_days integer DEFAULT 30,
  step4_subject text DEFAULT 'Time for your monthly check-in'::text,
  step4_template text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT followup_sequence_settings_pkey PRIMARY KEY (id),
  CONSTRAINT followup_sequence_settings_clinic_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.followup_tasks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  patient_id uuid NOT NULL,
  appointment_id uuid NOT NULL,
  step integer NOT NULL CHECK (step = ANY (ARRAY[1, 2, 3, 4])),
  scheduled_at timestamp with time zone NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'sent'::text, 'failed'::text, 'cancelled'::text])),
  sent_at timestamp with time zone,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT followup_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT followup_tasks_clinic_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT followup_tasks_patient_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT followup_tasks_appointment_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id)
);
CREATE TABLE public.no_show_predictions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  appointment_id uuid NOT NULL UNIQUE,
  patient_id uuid NOT NULL,
  risk_score numeric NOT NULL CHECK (risk_score >= 0::numeric AND risk_score <= 1::numeric),
  risk_level text NOT NULL CHECK (risk_level = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])),
  factors jsonb DEFAULT '{}'::jsonb,
  model_version text DEFAULT 'v1'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT no_show_predictions_pkey PRIMARY KEY (id),
  CONSTRAINT no_show_predictions_clinic_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT no_show_predictions_appointment_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT no_show_predictions_patient_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id)
);
CREATE TABLE public.revenue_snapshots (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  snapshot_date date NOT NULL,
  period_type text DEFAULT 'daily'::text CHECK (period_type = ANY (ARRAY['daily'::text, 'weekly'::text, 'monthly'::text])),
  gross_revenue numeric DEFAULT 0,
  net_revenue numeric DEFAULT 0,
  cancelled_revenue_loss numeric DEFAULT 0,
  no_show_revenue_loss numeric DEFAULT 0,
  avg_revenue_per_patient numeric DEFAULT 0,
  top_service_id uuid,
  top_service_name text,
  top_service_revenue numeric DEFAULT 0,
  slot_utilization_rate numeric DEFAULT 0,
  new_patient_revenue numeric DEFAULT 0,
  returning_patient_revenue numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT revenue_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT revenue_snapshots_clinic_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.copilot_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL UNIQUE,
  is_enabled boolean DEFAULT true,
  report_frequency text DEFAULT 'monthly'::text CHECK (report_frequency = ANY (ARRAY['weekly'::text, 'monthly'::text])),
  send_email boolean DEFAULT true,
  show_revenue_trends boolean DEFAULT true,
  show_patient_retention boolean DEFAULT true,
  show_service_performance boolean DEFAULT true,
  show_slot_utilization boolean DEFAULT true,
  show_recommendations boolean DEFAULT true,
  last_report_sent_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT copilot_settings_pkey PRIMARY KEY (id),
  CONSTRAINT copilot_settings_clinic_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.dynamic_pricing_rules (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  service_id uuid,
  rule_type text NOT NULL CHECK (rule_type = ANY (ARRAY['peak'::text, 'off_peak'::text, 'early_bird'::text, 'last_minute'::text])),
  day_of_week ARRAY DEFAULT '{}'::integer[],
  start_time time without time zone,
  end_time time without time zone,
  adjustment_type text DEFAULT 'percentage'::text CHECK (adjustment_type = ANY (ARRAY['percentage'::text, 'fixed'::text])),
  adjustment_value numeric NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dynamic_pricing_rules_pkey PRIMARY KEY (id),
  CONSTRAINT dynamic_pricing_rules_clinic_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT dynamic_pricing_rules_service_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.voice_call_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL,
  patient_id uuid,
  session_id text NOT NULL,
  duration_seconds integer DEFAULT 0,
  transcript text,
  intent_detected text,
  booking_completed boolean DEFAULT false,
  appointment_id uuid,
  language_used text DEFAULT 'en'::text,
  started_at timestamp with time zone DEFAULT now(),
  ended_at timestamp with time zone,
  CONSTRAINT voice_call_logs_pkey PRIMARY KEY (id),
  CONSTRAINT voice_call_logs_clinic_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT voice_call_logs_patient_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT voice_call_logs_appointment_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id)
);
CREATE TABLE public.language_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinic_id uuid NOT NULL UNIQUE,
  default_language text DEFAULT 'en'::text CHECK (default_language = ANY (ARRAY['en'::text, 'hi'::text])),
  auto_detect boolean DEFAULT true,
  supported_languages ARRAY DEFAULT '{en,hi}'::text[],
  widget_greeting_en text,
  widget_greeting_hi text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT language_settings_pkey PRIMARY KEY (id),
  CONSTRAINT language_settings_clinic_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);